### ISSUE TITLE
new npm beta needed.

### ISSUE THREAD

**Issue by bySabi** [barbatus/meteor-typescript#1]
Hi @barbatus.
In order to test new WIP typescript `path mappings`[https://github.com/Microsoft/TypeScript/issues/5039 ] and meteor  we need a new `meteor-typescript` npm who depend on typescript dev release.
 Ex: 
 "typescript": "1.9.0-dev.20160225"

Can you pubish a new one??

**Comment by barbatus** [comment]
TS 1.8 is not even added. I'll update it to 1.8.5 on this week, and then will see.

**Comment by bySabi** [comment]
1.8.5 is not enough for `path mappings`. This feature is merged on development branch `1.9` and scheduled for Typescript 2.0 release.

**Comment by barbatus** [comment]
So what? If you want with particular version now, you can just fork the package and add it for your needs.

**Comment by bySabi** [comment]
yes but then I need to publish my own `npm` meteor-typescript. I can´t not test this fork locally cause `Npm.depends` module resolution constrictions.
I thought is more suitable that you publish a beta version of it.

**Comment by barbatus** [comment]
try to fork and reference a repo in Npm.depends (like this https://github.com/Urigo/angular2-meteor/blob/master/atmosphere-packages/angular2-meteor/package.js#L9).

**Comment by bySabi** [comment]
Good!! I'll try this.
Thanks.

**Comment by bySabi** [comment]
Hi @barbatus I know is not your concern but maybe you know what happend.
I cloned `typescript-compiler` on local `packages` of a demo repo and change this ...

package.js

```
Npm.depends({
  'meteor-typescript': '0.6.0-beta.2',
  'async': '1.4.0'
});

```

to this ...

```
Npm.depends({
  'meteor-typescript': 'https://github.com/barbatus/meteor-typescript/tarball/afcc70c22158cf4a39d24a42ae37afb8787816c',
  'async': '1.4.0'
});
```

but get error: 

```
 package.js:9:5: must declare valid version of dependency: meteor-typescript@https://github.com/barbatus/meteor-typescript/tarball/afcc70c22158cf4a39d24a42ae37afb8787816c
```

I check URL on browser and is working fine. I try add this line to `Npm.depends` 

```
'angular2-meteor': 'https://github.com/Urigo/angular2-meteor/tarball/0c07434635eedd347854ec05ab3fc20ecfe732a0',
```

and is fine too. 

What could be happend here??

**Comment by barbatus** [comment]
what if you add api.versionsFrom('1.2.1')?

**Comment by bySabi** [comment]
api.versionsFrom('1.2.1') not make any difference.

 Actually 

```
'meteor-typescript': 'https://github.com/barbatus/meteor-typescript/tarball/afcc70c22158cf4a39d24a42ae37afb8787816c'
```

correspond to 

```
'meteor-typescript': '0.6.0-beta.2',
```

are the same npm commit.

Maybe a meteor package npm resolution bug??

**Comment by bySabi** [comment]
I create meteor-typescript tarball URL again and it works. Probably was a hidden character from copy-paste.

**Comment by bySabi** [comment]
@barbatus changing Npm.depends `meteor-typescript` to what ever npm tarball link gave me this error:

```
packages/typescript-compiler/.npm/package/node_modules/meteor-typescript/index.js:87:11: fileContent should be a string
```

I guest the fork way "not way".
 Maybe you could create a `meteor-typescript@next` npm changing `package.json` to ...

```
  "dependencies": {
    "typescript": "next",
...
  },
```

**Comment by barbatus** [comment]
Ok, I set it to `next` for time being.
