### ISSUE TITLE
useCache

### ISSUE THREAD

**Issue by portah** [barbatus/meteor-typescript#2]
I do not know is it exactly this module or not. I used instructions for meteor 1.3 and this module was installed.

Here is my issue. 
I have a file something.ts in project/common directory. So it runs in client and server. When I change the file the client always has the latest version but the server keeps the first version. If I cleanup ~/.typescript-cache then meteor  recompiles the file and server has current version, till I change something. If I force option.useCache = false. Then at least after meteor restart I have latest recompile version.

**Comment by barbatus** [comment]
thanks!

**Comment by portah** [comment]
Thanks to you too, going to check :) :+1:
