### ISSUE TITLE
Getting different errors than when running tsc -p .

### ISSUE THREAD

**Issue by realyze** [barbatus/meteor-typescript#5]
For some reason I'm getting some `"'xxx' does not exists in module "yyy"` errors when compiling via `barbatus:typescript`. It's an older project and it's using TS 1.5 modules (i.e., not ES6 modules).

Should the  output be exactly the same or is it expected that the module lookup works differently when using the meteor plugin?

(BTW kudos for the awesome work on this package, @barbatus )

**Comment by barbatus** [comment]
In this case there should be set `module:none` in `tsconfig.json`.
Please try, if doesn't work then I'll need an example repo to see how do you use this type of modules.
